

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on new releases
  release:
    types: [released]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Updates your service on PanQK
      - uses: /PlanQK/update-service-action@v1.2.0
        with:
          PLANQK_TOKEN: hallo
          CONTEXT_ID: welt
